### ISSUE TITLE
Query summary does not show join operator

### ISSUE THREAD

**Issue by ofirmanor** [dataflint/spark#1]
(been playing a bit, this tool looks pretty cool, thanks for sharing it!)

tried with a basic 2-way join and some aggregate (on TPCDS tableS).
When viewing a SQL query (summary --> clicking a query), the join operator (ShuffledHashJoin) is presented as SELECT, both in BASIC view
![image](https://github.com/dataflint/spark/assets/5271055/49456006-df72-4c34-9b6b-7bcea2c8ea4f)
and in ADVANCED view
![image](https://github.com/dataflint/spark/assets/5271055/b583f178-ef0e-4514-87c1-768a3c274f9c)

I am playing with Spark 3.5.0, this is the physical plan:
```
AdaptiveSparkPlan (31)
+- == Final Plan ==
   TakeOrderedAndProject (20)
   +- * HashAggregate (19)
      +- AQEShuffleRead (18)
         +- ShuffleQueryStage (17), Statistics(sizeInBytes=399.0 KiB, rowCount=1.28E+4)
            +- Exchange (16)
               +- * HashAggregate (15)
                  +- * Project (14)
                     +- * ShuffledHashJoin Inner BuildRight (13)
                        :- AQEShuffleRead (6)
                        :  +- ShuffleQueryStage (5), Statistics(sizeInBytes=87.9 MiB, rowCount=2.88E+6)
                        :     +- Exchange (4)
                        :        +- * Filter (3)
                        :           +- * ColumnarToRow (2)
                        :              +- Scan parquet  (1)
                        +- AQEShuffleRead (12)
                           +- ShuffleQueryStage (11), Statistics(sizeInBytes=281.3 KiB, rowCount=1.80E+4)
                              +- Exchange (10)
                                 +- * Filter (9)
                                    +- * ColumnarToRow (8)
                                       +- Scan parquet  (7)
```
This is how Spark draws it
![image](https://github.com/dataflint/spark/assets/5271055/05fb1bea-b39f-489c-987c-92ffbb1dd074)

**Comment by menishmueli** [comment]
Hi @ofirmanor, thanks for the feedback!

You were right, DataFlint didn't supported ShuffledHashJoin. It will be fixed from the next version (or you can use the snapshot version at 0.1.0-SNAPSHOT)

I would also really appreciate once you use DataFlint some more to hear your complete feedback at [DataFlint slack channel](https://join.slack.com/t/dataflint/shared_invite/zt-28sr3r3pf-Td_mLx~0Ss6D1t0EJb8CNA)
