### ISSUE TITLE
Cannot access dataflint UI through Knox gateway URL

### ISSUE THREAD

**Issue by anle20** [dataflint/spark#13]
**Describe the bug**
Currently, we are using Spark on AWS EMR. We are also using Knox Apache gateway as a gateway for our cluster, we will access spark history, livy, and dataflint through Knox gateway URL. But after installing successfully dataflint on our EMR, we cannot access it. After I checked it, I saw that data-flint is trying to call API directly without through gateway.

GET https://<url>/api/v1/applications/<application_id/1/environment 404 (Not Found)

it should be call to: https://<url>/gateway/<name>/sparkhistory/history/<application_id>/1/environment/

So I think it might be from this config: https://github.com/dataflint/spark/blob/main/spark-ui/src/services/SparkApi.tsx#L78-L80

Please help to check it. 

Thanks in advance

**Environemnt**
spark verison: 3.4.1
platform: EMR

**To Reproduce**
Steps to reproduce the behavior: it's hard to reproduce, we need to install knox apache gateway

**Expected behavior**
Dataflint UI should be loaded successfully

**Screenshots**
![IMG_3495](https://github.com/user-attachments/assets/af41c267-0904-494a-b48e-1e778be88b82)

**Comment by menishmueli** [comment]
Hi @anle20, really sorry for missing your issue. Did you manage to fix your problem?

**Comment by anle20** [comment]
Hi @menishmueli , Thanks for your response. Regarding this issue, we resolved it by rewriting Knox Gateway. But we've got other problems.
1/When we click "TO HISTORY SERVER", it cannot back to the spark history page. 
for example: 
spark history page:  https://knox.com/gateway/sparkhistory
dataflint: https://knox.com/gateway/sparkhistory/history/<application_id>/dataflint
-> When clicking to SPARK HISTORY, it will access to: https://knox.com/history instead of https://knox.com/gateway/sparkhistory
I think it is related to this code: [spark history page](https://github.com/dataflint/spark/blob/main/spark-ui/src/components/AppDrawer/DrawerFooter.tsx#L9-L16)

2/ The logo.png cannot load

**Comment by ef1236** [comment]
@anle20 I have encountered the exact same problem. can you elaborate on what did you change in the knox gateway. I am trying to use the latest version(currently 0.2.5)

**Comment by anle20** [comment]
Hi @ef1236 , you need to rewrite your service.xml and rewrite.xml on your knox to route all requests to /api/v1 -> sparkhistory/api/v1.
