### ISSUE TITLE
Support to turn off auto refresh

### ISSUE THREAD

**Issue by barunpuri** [dataflint/spark#7]
**Describe the bug**
~A clear and concise description of what the bug is.~
It's not a bug, but improvement

**Environemnt**
spark verison: 3.2/
platform: standalone

**To Reproduce**
1. Submit spark query 
2. Open spark history page
3. Open Dataflint
4. It refresh page automatically

**Expected behavior**
Could Turn off auto-refresh 

**Screenshots**

https://github.com/dataflint/spark/assets/12489812/28db053b-d0d5-4c39-8e39-737864e3295d

As you can see, data has been updating

**Additional context**

**Comment by menishmueli** [comment]
Hi @barunpuri!

The source of the issue is not "auto refresh", as when DataFlint in history server mode it doesn't refresh (there is no reason to). 
There is a server error and the error is not indicative (because it's the same error as when using DataFlint on spark driver and the server stopped responding, for example because the spark session ended)

Can you please in your browser open the inspect window, and show to me the output of the console and network tabs? and for any failed network request, show the error?

**Comment by barunpuri** [comment]
> Hi @barunpuri!
> 
> The source of the issue is not "auto refresh", as when DataFlint in history server mode it doesn't refresh (there is no reason to). There is a server error and the error is not indicative (because it's the same error as when using DataFlint on spark driver and the server stopped responding, for example because the spark session ended)
> 
> Can you please in your browser open the inspect window, and share the output of the console and network tabs? and for any failed network request, show the error?
> 
> Thanks!

Well I see. 
Thank you for response. 
Request for history server failed.
`GET http://___history_server___/proxy/___application_id____/api/v1/applications/___application_id____/sql?offset=0&length=1000&planDescription=false`
Response
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Request failed.</title>
</head>
<body><h2>HTTP ERROR 500 Request failed.</h2>
<table>
<tr><th>URI:</th><td>/api/v1/applications/___application_id____/sql</td></tr>
<tr><th>STATUS:</th><td>500</td></tr>
<tr><th>MESSAGE:</th><td>Request failed.</td></tr>
<tr><th>SERVLET:</th><td>org.glassfish.jersey.servlet.ServletContainer-49154699</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>

</body>
</html>
```

**Comment by menishmueli** [comment]
The request that is failing with 500 is GET request for an official Spark REST API endpoint
<img width="1210" alt="image" src="https://github.com/dataflint/spark/assets/11976579/76896481-70d7-4f02-a94b-3a9fedf0b38c">
(Source: https://spark.apache.org/docs/latest/monitoring.html)

I got multiple reports so far that this request tends to sometimes fail in spark 3.2, seems like there is a bug in spark that was solved in later versions.

If it's possible, you could upgrade your history server version to the latest spark version (3.5) and I believe it would solve the problem. History server is backward compatible so it could show you runs that was submitted with spark 3.2.

Could you also please look at your history server logs and share the exception that resulted in error 500?

**Comment by barunpuri** [comment]
> The request that is failing with 500 is GET request for an official Spark REST API endpoint <img alt="image" width="1210" src="https://private-user-images.githubusercontent.com/11976579/301453787-76896481-70d7-4f02-a94b-3a9fedf0b38c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MzQ5MTksIm5iZiI6MTcwNjgzNDYxOSwicGF0aCI6Ii8xMTk3NjU3OS8zMDE0NTM3ODctNzY4OTY0ODEtNzBkNy00ZjAyLWE5NGItM2E5ZmVkZjBiMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDAwNDMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMWEzZTY0NDlkZjhiOTFhYzJhZWNhZGI3N2JmOWE1NTU2YTY0NzU4NzYxYWE3MzUwYWRlMjliODM2ZTkzOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j_9IwW-GiwQBKWffpVxdB8Hg-YDG9W4at19kY24c0yE"> (Source: [spark.apache.org/docs/latest/monitoring.html](https://spark.apache.org/docs/latest/monitoring.html))
> 
> I got multiple reports so far that this request tends to sometimes fail in spark 3.2, seems like there is a bug in spark that was solved in later versions.
> 
> If it's possible, you could upgrade your history server version to the latest spark version (3.5) and I believe it would solve the problem. History server is backward compatible so it could show you runs that was submitted with spark 3.2.
> 
> Could you also please look at your history server logs and share the exception that resulted in error 500?

Thank you for your kind response.
For now, it's hard to test with 3.5 cus it's managed by a different team.
So if it resolved this issue could be closed. Thank you
